coverage:
  range: 50..70

comment:
  layout: "header, diff, flags, components"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_fastlane
      name: fastlane
      paths:
        - pkgs/fastlane/**
    - component_id: module_flutter
      name: flutter
      paths:
        - pkgs/flutter/**
