dependencies:
    cupertino_icons: ^1.0.0
    english_words: ^4.0.0
    flutter:
        sdk: flutter
    go_router: ^13.0.0
    http: ^1.0.0
    intl: ^0.19.0
    json_annotation: any
    window_size:
        git:
            path: plugins/window_size
            url: https://github.com/google/flutter-desktop-embedding.git
description: A sample demonstrating different types of forms and best practices
dev_dependencies:
    analysis_defaults:
        path: ../analysis_defaults
    build_runner: ^2.1.8
    flutter_test:
        sdk: flutter
    json_serializable: ^6.2.0
environment:
    sdk: ^3.2.0
flutter:
    uses-material-design: true
name: form_app
publish_to: none
version: 0.1.4+233
